# Generated by Django 5.2.5 on 2025-09-07 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreh', '0003_appointment_is_paid_appointment_payment_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_paid',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='payment_reference',
            new_name='paystack_ref',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='subservice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loreh.subservice'),
        ),
    ]
