# Generated by Django 5.2.5 on 2025-09-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreh', '0004_rename_is_paid_appointment_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='created',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated',
        ),
        migrations.AddField(
            model_name='subservice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
