# Generated by Django 5.2.5 on 2025-09-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loreh', '0006_remove_service_description_alter_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
